# Generated by Django 3.1.7 on 2021-03-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20210316_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationletter',
            old_name='groupName',
            new_name='group_name',
        ),
    ]
