# Generated by Django 3.1.7 on 2021-05-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_auto_20210522_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
