# Generated by Django 3.1.7 on 2021-05-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_donation_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='country',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='zip_code',
            field=models.TextField(blank=True, max_length=5),
        ),
    ]
