# Generated by Django 3.1.7 on 2021-05-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_auto_20210522_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='form_data',
            field=models.JSONField(blank=True),
        ),
    ]
