# Generated by Django 3.1.7 on 2021-05-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_auto_20210522_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
