# Generated by Django 3.1.7 on 2021-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_auto_20210522_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
