# Generated by Django 3.1.7 on 2021-05-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0015_auto_20210522_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='pdf',
        ),
        migrations.AddField(
            model_name='donation',
            name='link_to_pdf',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
