# Generated by Django 3.1.7 on 2021-10-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0018_auto_20211027_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='donor',
            name='country',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='donor',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='donor',
            name='zip_code',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
