# Generated by Django 3.1.7 on 2021-10-27 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0019_auto_20211027_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.donor'),
        ),
    ]
