# Generated by Django 3.1.7 on 2021-10-28 15:53

from django.db import migrations

def extract_organization(apps, schema_editor):
    Organization = apps.get_model("donations", "Organization")
    Donation = apps.get_model("donations", "Donation")
    for donation in Donation.objects.exclude(organization_name__exact=""):
        organization = Organization(
            name = donation.organization_name,
            fo_number = donation.organization_fo_number,
            address = donation.organization_address,
            zip_code = donation.organization_zip_code,
            city = donation.organization_city,
            country = donation.organization_country
        )
        organization.save()
        donation.organization = organization
        donation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0021_auto_20211028_1553'),
    ]

    operations = [
        migrations.RunPython(extract_organization)
    ]
