# Generated by Django 3.1.7 on 2021-10-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0022_auto_20211028_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='organization_address',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='organization_city',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='organization_country',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='organization_fo_number',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='organization_zip_code',
        ),
    ]
