# Generated by Django 3.1.7 on 2021-10-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0023_auto_20211028_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donation',
            new_name='DonationLetter',
        ),
    ]
