# Generated by Django 3.1.7 on 2021-10-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0025_auto_20211028_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationletter',
            name='pseudonym',
        ),
    ]
