# Generated by Django 3.1.7 on 2021-10-28 16:38

from django.db import migrations

def extract_donations(apps, schema_editor):
    Donation = apps.get_model("donations", "Donation")
    DonationLetter = apps.get_model("donations", "DonationLetter")
    for donation_letter in DonationLetter.objects.all():
        donation = Donation(
            donor = donation_letter.donor,
            organization = donation_letter.organization,
            visibility = donation_letter.donation_visibility,
            sum = donation_letter.donation_sum,
            greeting = donation_letter.greeting,
            group_name = donation_letter.group_name
        )
        donation.save()
        donation_letter.donation = donation
        donation_letter.save()

class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0027_auto_20211028_1637'),
    ]

    operations = [
        migrations.RunPython(extract_donations)
    ]
