# Generated by Django 3.1.7 on 2021-10-30 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0027_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationletter',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.contribution'),
        ),
    ]
