# Generated by Django 3.1.7 on 2021-10-30 10:05

from django.db import migrations

def extract_contributions(apps, schema_editor):
    Contribution = apps.get_model("donations", "Contribution")
    DonationLetter = apps.get_model("donations", "DonationLetter")
    for donation_letter in DonationLetter.objects.all():
        contribution = Contribution(
            donor = donation_letter.donor,
            organization = donation_letter.organization,
            visibility = donation_letter.donation_visibility,
            sum = donation_letter.donation_sum,
            greeting = donation_letter.greeting,
            group_name = donation_letter.group_name
        )
        contribution.save()
        donation_letter.contribution = contribution
        donation_letter.save()

class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0028_donationletter_contribution'),
    ]

    operations = [
        migrations.RunPython(extract_contributions)
    ]
