# Generated by Django 3.1.7 on 2021-11-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0030_auto_20211030_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.CharField(max_length=250),
        ),
    ]
