# Generated by Django 3.1.7 on 2022-01-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0031_auto_20211106_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donation_mark_rfid',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
