# Generated by Django 3.2.11 on 2022-01-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0032_donor_donation_mark_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='visibility',
            field=models.TextField(choices=[['visible', 'visible'], ['pseudonym', 'pseudonym'], ['anonymous', 'anonymous']]),
        ),
    ]
