# Generated by Django 3.1.7 on 2021-03-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('zip_code', models.TextField(max_length=5)),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('organization_name', models.TextField(blank=True)),
                ('organization_fo_number', models.TextField(blank=True)),
                ('organization_address', models.TextField(blank=True)),
                ('organization_zip_code', models.TextField(blank=True, max_length=5)),
                ('organization_city', models.TextField(blank=True)),
                ('organization_country', models.TextField(blank=True)),
                ('payment_date', models.DateField()),
                ('donation_sum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('visibility', models.TextField(choices=[['visible', 'visible'], ['pseudonym', 'pseudonym'], ['anonymous', 'anonymous']])),
                ('pseudonym', models.TextField(blank=True)),
                ('groupName', models.TextField(blank=True)),
                ('greeting', models.TextField(blank=True)),
            ],
        ),
    ]
