# Generated by Django 3.1.7 on 2021-03-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationletter',
            name='donation_letter',
            field=models.BinaryField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationletter',
            name='form_data',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
