# Generated by Django 3.1.7 on 2021-03-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20210316_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationletter',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
