# Generated by Django 3.1.7 on 2021-03-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20210316_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationletter',
            old_name='visibility',
            new_name='donation_visibility',
        ),
    ]
