"""
Django settings for donationdb project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import dotenv
from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DONATIONDB_DEBUG", "True") == "True"
CI = os.environ.get("CI", "False") == "True"

if DEBUG == True and CI != True:
    print("Reading environment variables from ../.env")
    dotenv.read_dotenv("../.env")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DONATIONDB_SECRET_KEY"] if DEBUG == False else "foobar"
API_KEY = os.environ["DONATIONDB_API_KEY"] if DEBUG == False else "foobar"
DONATIONDB_URL = os.environ["DONATIONDB_URL"]
FRONTEND_URL = os.environ["FRONTEND_URL"]
SENDGRID_API_KEY = os.environ["SENDGRID_API_KEY"]
PAYTRAIL_ACCOUNT_ID = os.environ["PAYTRAIL_ACCOUNT_ID"]
PAYTRAIL_ACCOUNT_SECRET = os.environ["PAYTRAIL_ACCOUNT_SECRET"]

if DEBUG:
    ALLOWED_HOSTS = ["localhost", "staging-barsborsen.herokuapp.com"]
else:
    ALLOWED_HOSTS = ["barsborsen.herokuapp.com", "vision.tf.fi", "barsborsen.tf.fi"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'donations',
    'pages',
    'payments',
    'rest_framework'
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'donationdb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'donationdb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {}
if CI == True:
    DATABASES['default'] = {
         'ENGINE': 'django.db.backends.sqlite3',
         'NAME': BASE_DIR / 'db.sqlite3',
     }
elif DEBUG == True:
    DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=False)
else:
    DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True)

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

if DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "https://staging-vision-tf-fi.herokuapp.com",
        "http://donationdb.local:8000",
        "http://localhost:8000"
    ]
else:
    CORS_ALLOWED_ORIGINS = [
        "https://vision-tf-fi.herokuapp.com",
        "https://vision.tf.fi"
    ]
