# Generated by Django 3.1.7 on 2021-11-06 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0031_auto_20211106_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=50)),
                ('status', models.TextField(choices=[['new', 'new'], ['ok', 'ok'], ['fail', 'fail'], ['pending', 'pending'], ['delayed', 'delayed']])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='donations.contribution')),
            ],
        ),
    ]
