# Generated by Django 3.1.7 on 2021-11-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0031_auto_20211106_1629'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Transaction',
        ),
    ]
