# Generated by Django 3.1.7 on 2021-11-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20211107_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction',
            new_name='checkout_transaction_id',
        ),
    ]
